/*
* Copyright 2026 Rochus Keller <mailto:me@rochus-keller.ch>
*
* This file is part of the AIR (Algol Intermediate Representation) library.
*
* The following is the license that applies to this copy of the
* file. For a license to use the file under conditions
* other than those described here, please email to me@rochus-keller.ch.
*
* GNU General Public License Usage
* This file may be used under the terms of the GNU General Public
* License (GPL) versions 2.0 or 3.0 as published by the Free Software
* Foundation and appearing in the file LICENSE.GPL included in
* the packaging of this file. Please review the following information
* to ensure GNU General Public Licensing requirements will be met:
* http://www.fsf.org/licensing/licenses/info/GPLv2.html and
* http://www.gnu.org/copyleft/gpl.html.
*/

#include <Algol60/AirRenderer.h>
#include <Algol60/AirOps.h>
#include <QCoreApplication>
#include <QDateTime>
#include <QtDebug>
using namespace Air;
using Alg::RowCol;

enum { MaxLineLen = 72 };

static const char* s_basicName[] = {
    "?undefined?",
    "bool", "char", "int8", "int16", "int32", "int64",
    "uint8", "uint16", "uint32", "uint64", "float32", "float64", "task", "anyrec",
    "?max?"
};

const char* EmiTypes::basicName(quint8 t)
{
    if( t >= MaxBasic )
        return s_basicName[0];
    return s_basicName[t];
}

AsmRenderer::AsmRenderer(QIODevice* dev, bool renderLineInfo, bool renderColumns):
    state(Idle),curSection(None),typeKind(EmiTypes::Invalid),level(0),
    typeIsPublic(false),renderLineInfo(renderLineInfo),renderColumns(renderColumns)
{
    out.setDevice(dev);
}

void AsmRenderer::beginModule(const QByteArray& name, const QString& sourceFile)
{
    moduleName = name;
    out << "// Generated by " << qApp->applicationName() << " " << qApp->applicationVersion()
        << " on " << QDateTime::currentDateTime().toString(Qt::ISODate) << endl << endl;
    out << "MODULE" << lineout() << " " << name << endl;
    state = Module;
    level++;
    if( !sourceFile.isEmpty() )
        out << ws() << "SOURCE " << formatString(sourceFile.toUtf8()) << endl;
}

void AsmRenderer::endModule()
{
    curSection = None;
    level--;
    out << "END" << lineout() << " " << moduleName << endl;
    state = Idle;
}

void AsmRenderer::addImport(const QByteArray& name)
{
    curSection = None;
    out << ws() << "IMPORT " << name << endl;
}

void AsmRenderer::section(quint8 s)
{
    if( curSection == s )
        return;
    curSection = s;
    switch( s )
    {
    case ConstSection:
        out << ws() << "CONST" << endl;
        break;
    case TypeSection:
        out << ws() << "TYPE" << endl;
        break;
    case VarSection:
        out << ws() << "VAR" << endl;
        break;
    }
}

void AsmRenderer::addVariable(const Quali& typeRef, const QByteArray& name, bool isPublic)
{
    section(VarSection);
    out << ws() << "   " << name << (isPublic ? "*" : "") << ": " << shortName(typeRef) << endl;
}

void AsmRenderer::addConst(const Quali& typeRef, const QByteArray& name, const QVariant& val)
{
    section(ConstSection);
    out << ws() << "   " << name << " = ";
    if( val.type() == QVariant::ByteArray || val.type() == QVariant::String )
        out << formatString(val.toByteArray());
    else
        out << formatNumber(val);
    out << endl;
}

void AsmRenderer::beginType(const QByteArray& name, bool isPublic, quint8 kind, const Quali& base)
{
    section(TypeSection);
    typeName = name;
    typeIsPublic = isPublic;
    typeKind = kind;
    typeBase = base;
    fields.clear();
    state = Struct;
}

void AsmRenderer::addField(const QByteArray& fieldName, const Quali& typeRef, bool isPublic)
{
    if( state != Struct )
    {
        addVariable(typeRef, fieldName, isPublic);
        return;
    }
    ProcData::Var f(typeRef, fieldName, 0);
    f.isPublic = isPublic;
    fields.append(f);
}

QByteArray AsmRenderer::fieldList() const
{
    QByteArray res;
    for( int i = 0; i < fields.size(); i++ )
    {
        if( i != 0 )
        {
            if( fields[i].type == fields[i-1].type && fields[i].isPublic == fields[i-1].isPublic )
            {
                res += ", " + fields[i].name + (fields[i].isPublic ? "*" : "");
                continue;
            }
            res += ": " + shortName(fields[i-1].type) + "; ";
        }
        res += fields[i].name;
        if( fields[i].isPublic )
            res += "*";
    }
    if( !fields.isEmpty() )
        res += ": " + shortName(fields.back().type);
    return res;
}

void AsmRenderer::renderFields()
{
    if( fields.isEmpty() )
        return;
    level++;
    for( int i = 0; i < fields.size(); i++ )
    {
        if( i != 0 && fields[i].type == fields[i-1].type && fields[i].isPublic == fields[i-1].isPublic )
            continue;
        int j = i;
        QByteArray names;
        while( j < fields.size() && fields[j].type == fields[i].type && fields[j].isPublic == fields[i].isPublic )
        {
            if( j != i )
                names += ", ";
            names += fields[j].name;
            if( fields[j].isPublic )
                names += "*";
            j++;
        }
        out << ws() << names << ": " << shortName(fields[i].type) << endl;
        i = j - 1;
    }
    level--;
}

void AsmRenderer::endType()
{
    const char* kw = typeKind == EmiTypes::Record ? "RECORD" :
                     typeKind == EmiTypes::CStruct ? "CSTRUCT" :
                     typeKind == EmiTypes::CUnion ? "CUNION" : "STRUCT";
    level++;
    QByteArray head = typeName + (typeIsPublic ? "*" : "") + " = " + kw;
    if( typeKind == EmiTypes::Record && !typeBase.second.isEmpty() )
        head += " (" + shortName(typeBase) + ")";
    const QByteArray all = fieldList();
    if( ws().size() + head.size() + all.size() + 5 <= MaxLineLen )
        out << ws() << head << (all.isEmpty() ? "" : " ") << all << " END" << endl;
    else
    {
        out << ws() << head << endl;
        renderFields();
        out << ws() << "END" << endl;
    }
    level--;
    fields.clear();
    typeKind = EmiTypes::Invalid;
    state = Module;
}

void AsmRenderer::addType(const QByteArray& name, bool isPublic, const Quali& baseType, quint8 kind, quint32 len)
{
    section(TypeSection);
    level++;
    out << ws() << name << (isPublic ? "*" : "") << " = ";
    switch( kind )
    {
    case EmiTypes::Alias:
        out << shortName(baseType);
        break;
    case EmiTypes::Pointer:
        out << "POINTER TO ";
        if( baseType.first.isEmpty() && baseType.second == EmiTypes::basicName(EmiTypes::ANYREC) )
            out << "ANYREC";
        else
            out << shortName(baseType);
        break;
    case EmiTypes::CPointer:
        out << "CPOINTER TO " << shortName(baseType);
        break;
    case EmiTypes::Array:
    case EmiTypes::CArray:
        out << (kind == EmiTypes::Array ? "ARRAY " : "CARRAY ");
        if( len )
            out << len << " ";
        out << "OF " << shortName(baseType);
        break;
    default:
        errors.append(Error());
        errors.back().msg = QString("invalid type kind %1").arg(kind);
        errors.back().where = name;
        break;
    }
    out << endl;
    level--;
}

void AsmRenderer::addProcedure(const ProcData& proc)
{
    if( proc.kind == ProcData::Invalid )
        return;
    render(proc);
}

QByteArray AsmRenderer::formals(const ProcData& proc) const
{
    QByteArray res = "(";
    int i = 0;
    while( i < proc.params.size() )
    {
        const ProcData::Var& p = proc.params[i];
        int j = i;
        QByteArray names;
        while( j < proc.params.size() && proc.params[j].type == p.type
               && proc.params[j].isVarParam == p.isVarParam && !proc.params[j].name.isEmpty() )
        {
            if( j != i )
                names += ", ";
            names += proc.params[j].name;
            j++;
        }
        if( i != 0 )
            res += "; ";
        if( p.isVarParam )
            res += "VAR ";
        if( names.isEmpty() )
        {
            res += shortName(p.type); // parameter of a procedure type without a name
            j = i + 1;
        }else
            res += names + ": " + shortName(p.type);
        i = j;
    }
    res += ")";
    if( !proc.retType.second.isEmpty() )
        res += ": " + shortName(proc.retType);
    return res;
}

void AsmRenderer::render(const ProcData& proc)
{
    if( proc.kind == ProcData::ProcType || proc.kind == ProcData::BoundProcType )
    {
        section(TypeSection);
        level++;
        out << ws() << proc.name << (proc.isPublic ? "*" : "") << " = PROCEDURE"
            << (proc.kind == ProcData::BoundProcType ? "^" : "") << formals(proc) << endl;
        level--;
        return;
    }

    curSection = None;
    out << endl << ws() << "PROCEDURE" << lineout() << " ";
    if( !proc.binding.isEmpty() && (proc.kind == ProcData::Normal || proc.kind == ProcData::Init) )
        out << proc.binding << ".";
    out << proc.name << (proc.isPublic ? "*" : "") << formals(proc);
    switch( proc.kind )
    {
    case ProcData::Init:
        out << " INIT";
        break;
    case ProcData::Extern:
    case ProcData::Foreign:
        out << (proc.kind == ProcData::Extern ? " EXTERN" : " FOREIGN");
        if( !proc.binding.isEmpty() )
            out << " " << formatString(proc.binding);
        out << endl;
        return;
    }
    out << endl;

    state = Proc;
    renderBody(proc);
    state = Module;
}

QByteArray AsmRenderer::argName(const ProcData& proc, const QVariant& arg, bool local) const
{
    const QList<ProcData::Var>& vars = local ? proc.locals : proc.params;
    const quint32 i = arg.toUInt();
    if( i < (quint32)vars.size() && !vars[i].name.isEmpty() )
        return vars[i].name;
    return QByteArray::number(i);
}

void AsmRenderer::renderBody(const ProcData& proc)
{
    if( !proc.locals.isEmpty() )
    {
        QByteArray decls;
        for( int i = 0; i < proc.locals.size(); i++ )
        {
            if( i != 0 )
                decls += "; ";
            decls += proc.locals[i].name.isEmpty() ? QByteArray::number(i) : proc.locals[i].name;
            decls += ": " + shortName(proc.locals[i].type);
        }
        out << ws() << "VAR " << decls << endl;
    }
    out << ws() << "BEGIN" << endl;

    level++;
    for( int i = 0; i < proc.body.size(); i++ )
    {
        const ProcData::Op& op = proc.body[i];
        QByteArray text = s_opName[op.op];
        switch( op.op )
        {
        case op_invalid:
            continue;
        case op_LINE:
            if( !renderLineInfo )
                continue;
            {
                const quint32 packed = op.arg.toUInt();
                const quint32 row = RowCol::unpackRow2(packed);
                const quint32 col = RowCol::unpackCol2(packed);
                if( row == lastPos.d_row && (!renderColumns || col == lastPos.d_col) )
                    continue;
                lastPos.setRowCol(row,col);
                text += " " + QByteArray::number(row);
                if( renderColumns )
                    text += ":" + QByteArray::number(col);
            }
            flush();
            emit_(text, true);
            continue;
        case op_iif:
        case op_IF:
        case op_LOOP:
        case op_REPEAT:
        case op_SWITCH:
        case op_WHILE:
            flush();
            emit_(text, true);
            flush();
            level++;
            continue;
        case op_THEN:
        case op_ELSE:
        case op_UNTIL:
        case op_DO:
            flush();
            level--;
            emit_(text, true);
            flush();
            level++;
            continue;
        case op_END:
            flush();
            level--;
            emit_(text, true);
            flush();
            continue;
        case op_CASE:
            flush();
            level--;
            {
                const CaseLabelList labels = op.arg.value<CaseLabelList>();
                for( int j = 0; j < labels.size(); j++ )
                {
                    const CaseLabel& l = labels[j];
                    text += (j == 0 ? " " : ", ") + QByteArray::number(l.first);
                    if( l.second != l.first )
                        text += ".." + QByteArray::number(l.second);
                }
            }
            emit_(text + " THEN", true);
            flush();
            level++;
            continue;
        case op_ldarg:
        case op_starg:
        case op_refarg:
            text += " " + argName(proc, op.arg, false);
            break;
        case op_ldloc:
        case op_stloc:
        case op_refloc:
            text += " " + argName(proc, op.arg, true);
            break;
        case op_ldstr:
            text += " " + formatString(op.arg.toByteArray());
            break;
        case op_ldc_r4:
        case op_ldc_r8:
        case op_ldc_i4:
        case op_ldc_i8:
            text += " " + formatNumber(op.arg);
            break;
        default:
            if( op.arg.canConvert<Trident>() )
                text += " " + shortName(op.arg.value<Trident>());
            else if( op.arg.canConvert<Quali>() )
                text += " " + shortName(op.arg.value<Quali>());
            else if( !op.arg.isNull() )
                text += " " + op.arg.toByteArray();
            break;
        }
        emit_(text);
        if( isStatOp((Op)op.op) )
            flush();
    }
    flush();
    level--;

    out << ws() << "END " << proc.name << endl;
}

void AsmRenderer::emit_(const QByteArray& text, bool ownLine)
{
    if( ownLine )
        flush();
    if( !pending.isEmpty() && ws().size() + pending.size() + text.size() + 1 > MaxLineLen )
        flush();
    if( !pending.isEmpty() )
        pending += " ";
    pending += text;
    if( ownLine )
        flush();
}

void AsmRenderer::flush()
{
    if( pending.isEmpty() )
        return;
    out << ws() << pending << endl;
    pending.clear();
}

void AsmRenderer::line(const RowCol& pos)
{
    curPos = pos;
}

QByteArray AsmRenderer::lineout()
{
    if( !renderLineInfo || !curPos.isValid() )
        return QByteArray();
    if( curPos.d_row == lastPos.d_row && (!renderColumns || curPos.d_col == lastPos.d_col) )
        return QByteArray();
    lastPos = curPos;
    QByteArray res = " LINE " + QByteArray::number(curPos.d_row);
    if( renderColumns )
        res += ":" + QByteArray::number(curPos.d_col);
    return res;
}

QByteArray AsmRenderer::shortName(const Quali& q) const
{
    if( q.first.isEmpty() || q.first == moduleName )
        return q.second;
    return toString(q);
}

QByteArray AsmRenderer::shortName(const Trident& t) const
{
    return shortName(t.first) + "." + t.second;
}

QByteArray AsmRenderer::toString(const Quali& q)
{
    if( q.first.isEmpty() )
        return q.second;
    return q.first + "!" + q.second;
}

QByteArray AsmRenderer::toString(const Trident& t)
{
    return toString(t.first) + "." + t.second;
}

QByteArray AsmRenderer::formatNumber(const QVariant& v)
{
    switch( v.type() )
    {
    case QVariant::Double:
        break;
    case QVariant::ULongLong:
    case QVariant::UInt:
        return QByteArray::number(v.toULongLong());
    default:
        return QByteArray::number(v.toLongLong());
    }
    QByteArray tmp = QByteArray::number(v.toDouble(), 'g', 17);
    const int eidx = tmp.indexOf('e');
    if( eidx == -1 )
    {
        if( !tmp.contains('.') )
            tmp += ".0";
        return tmp;
    }
    QByteArray mantissa = tmp.left(eidx);
    if( !mantissa.contains('.') )
        mantissa += ".0";
    else if( mantissa.endsWith('.') )
        mantissa += "0";
    return mantissa + "E" + tmp.mid(eidx+1);
}

QByteArray AsmRenderer::formatString(const QByteArray& str)
{
    bool isPrint = true;
    for( int i = 0; i < str.size(); i++ )
    {
        if( (quint8)str[i] < ' ' || (quint8)str[i] > 126 )
        {
            isPrint = false;
            break;
        }
    }
    if( !isPrint )
        return "#" + str.toHex() + "#";
    if( str.contains('"') )
        return "'" + str + "'";
    return "\"" + str + "\"";
}

void RenderSplitter::beginModule(const QByteArray& moduleName, const QString& sourceFile)
{
    foreach( AbstractRenderer* r, renderer )
        r->beginModule(moduleName, sourceFile);
}

void RenderSplitter::endModule()
{
    foreach( AbstractRenderer* r, renderer )
        r->endModule();
}

void RenderSplitter::addImport(const QByteArray& moduleName)
{
    foreach( AbstractRenderer* r, renderer )
        r->addImport(moduleName);
}

void RenderSplitter::addVariable(const Quali& typeRef, const QByteArray& name, bool isPublic)
{
    foreach( AbstractRenderer* r, renderer )
        r->addVariable(typeRef, name, isPublic);
}

void RenderSplitter::addConst(const Quali& typeRef, const QByteArray& name, const QVariant& val)
{
    foreach( AbstractRenderer* r, renderer )
        r->addConst(typeRef, name, val);
}

void RenderSplitter::addProcedure(const ProcData& proc)
{
    foreach( AbstractRenderer* r, renderer )
        r->addProcedure(proc);
}

void RenderSplitter::beginType(const QByteArray& name, bool isPublic, quint8 typeKind, const Quali& base)
{
    foreach( AbstractRenderer* r, renderer )
        r->beginType(name, isPublic, typeKind, base);
}

void RenderSplitter::endType()
{
    foreach( AbstractRenderer* r, renderer )
        r->endType();
}

void RenderSplitter::addType(const QByteArray& name, bool isPublic, const Quali& baseType,
                             quint8 typeKind, quint32 len)
{
    foreach( AbstractRenderer* r, renderer )
        r->addType(name, isPublic, baseType, typeKind, len);
}

void RenderSplitter::addField(const QByteArray& fieldName, const Quali& typeRef, bool isPublic)
{
    foreach( AbstractRenderer* r, renderer )
        r->addField(fieldName, typeRef, isPublic);
}

void RenderSplitter::line(const RowCol& pos)
{
    foreach( AbstractRenderer* r, renderer )
        r->line(pos);
}
