#include <QCoreApplication>
#include <QFile>
#include <QtDebug>
#include <QFileInfo>
#include <QDir>
#include <QElapsedTimer>
#include <QThread>
#include <Algol60/AlgParser2.h>
#include <Algol60/AlgLexer.h>
#include <Algol60/AlgAst.h>
#include <Algol60/AlgValidator.h>
#include <Algol60/AlgAirGen.h>
#include <Algol60/AirRenderer.h>
#include <Algol60/AirAstRenderer.h>
#include <Algol60/AirAstSerializer.h>
#include <QBuffer>

static QStringList collectFiles( const QDir& dir )
{
    QStringList res;
    QStringList files = dir.entryList( QDir::Dirs | QDir::NoDotAndDotDot, QDir::Name );

    //foreach( const QString& f, files )
    //    res += collectFiles( QDir( dir.absoluteFilePath(f) ) );

    files = dir.entryList( QStringList() << QString("*.alg")
                                           << QString("*.al") << QString("*.a60"),
                                           QDir::Files, QDir::Name );
    foreach( const QString& f, files )
    {
        res.append( dir.absoluteFilePath(f) );
    }
    return res;
}

static void dumpAst( Alg::Declaration* module, const QString& path )
{
    QFile out( path + ".ast" );
    if( !out.open(QIODevice::WriteOnly) )
    {
        qCritical() << "cannot open for writing:" << out.fileName();
        return;
    }
    QTextStream ts(&out);
    Alg::AstModel::dump(ts, module);
}

static bool checkAir( const QString& path, Air::AstRenderer& ar, const QByteArray& direct )
{
    bool res = true;
    if( !ar.errors.isEmpty() )
    {
        foreach( const Air::AbstractRenderer::Error& e, ar.errors )
            qCritical() << "air:" << path << e.where << e.pc << e.msg;
        res = false;
    }
    Air::Declaration* module = ar.getModule();
    if( module == 0 )
        return false;

    QByteArray fromAst;
    QBuffer buf(&fromAst);
    buf.open(QIODevice::WriteOnly);
    Air::AsmRenderer r(&buf);
    Air::AstSerializer::render(&r, module, Air::AstSerializer::RowsOnly);
    buf.close();
    if( !r.errors.isEmpty() )
    {
        foreach( const Air::AbstractRenderer::Error& e, r.errors )
            qCritical() << "air serializer:" << path << e.where << e.pc << e.msg;
        res = false;
    }

    const QStringList l1 = QString::fromUtf8(direct).split('\n');
    const QStringList l2 = QString::fromUtf8(fromAst).split('\n');
    for( int i = 0; i < qMax(l1.size(),l2.size()); i++ )
    {
        const QString a1 = i < l1.size() ? l1[i] : QString();
        const QString a2 = i < l2.size() ? l2[i] : QString();
        if( a1 == a2 || a1.startsWith("// Generated by") ) // the header carries a timestamp
            continue;
        qCritical() << "air round-trip:" << path << "line" << i+1
                    << "direct:" << a1 << "ast:" << a2;
        res = false;
        break;
    }
    return res;
}

class Lex : public Alg::Scanner
{
public:
    Alg::Lexer lex;
    Alg::Token next()
    {
        return lex.nextToken();
    }

    Alg::Token peek(int offset)
    {
        return lex.peekToken(offset);
    }

    QString source() const
    {
        return lex.sourcePath();
    }
};

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    a.setOrganizationName("me@rochus-keller.ch");
    a.setOrganizationDomain("https://github.com/rochus-keller/Algol");
    a.setApplicationName("AlgLc");
    a.setApplicationVersion("2026-09-25");

    QTextStream out(stdout);
    out << "AlgLc version: " << a.applicationVersion() <<
                 " author: me@rochus-keller.ch  license: GPL" << endl;

    QStringList dirOrFilePaths;
    QString outPath;
    bool dump = false;
    QString ns;
    QString mod;
    bool air = false;
    bool rt = false;
    const QStringList args = QCoreApplication::arguments();
    for( int i = 1; i < args.size(); i++ ) // arg 0 enthaelt Anwendungspfad
    {
        if(  args[i] == "-h" || args.size() == 1 )
        {
            out << "usage: AlgLc [options] sources" << endl;
            out << "  reads Algol60 sources (files or directories) and translates them to corresponding Lua code." << endl;
            out << "options:" << endl;
            out << "  -dst      dump abstract syntax trees to files" << endl;
            out << "  -air      generate AIR files" << endl;
            out << "  -rt       generate the Algol60Rt interface module" << endl;
            out << "  -o=path   path where to save generated files (default like first source)" << endl;
            out << "  -ns=name  namespace for the generated files (default empty)" << endl;
            out << "  -mod=name directory of the generated files (default empty)" << endl;
            out << "  -h        display this information" << endl;
            return 0;
        }else if( args[i] == "-dst" )
            dump = true;
        else if( args[i] == "-air" )
            air = true;
        else if( args[i] == "-rt" )
            rt = true;
        else if( args[i].startsWith("-o=") )
            outPath = args[i].mid(3);
        else if( args[i].startsWith("-ns=") )
            ns = args[i].mid(4);
        else if( args[i].startsWith("-mod=") )
            mod = args[i].mid(5);
        else if( !args[ i ].startsWith( '-' ) )
        {
            dirOrFilePaths += args[ i ];
        }else
        {
            qCritical() << "error: invalid command line option " << args[i] << endl;
            return -1;
        }
    }
    if( dirOrFilePaths.isEmpty() && !rt )
    {
        qWarning() << "no file or directory to process; quitting (use -h option for help)" << endl;
        return -1;
    }
    if( outPath.isEmpty() && rt )
        outPath = QDir::currentPath();

    QStringList files;
    foreach( const QString& path, dirOrFilePaths )
    {
        QFileInfo info(path);
        if( outPath.isEmpty() )
            outPath = info.isDir() ? info.absoluteFilePath() : info.absolutePath();
        if( info.isDir() )
            files += collectFiles( info.absoluteFilePath() );
        else
            files << path;
    }

    if( rt )
    {
        QFile f( QDir(outPath).absoluteFilePath("Algol60Rt.air") );
        if( f.open(QIODevice::WriteOnly) )
        {
            Air::AsmRenderer r(&f);
            Alg::AirGen::generateRuntime(&r);
        }else
            qCritical() << "cannot open for writing:" << f.fileName();
    }

    QElapsedTimer timer;
    timer.start();
    int ok = 0, valid = 0, generated = 0, airValid = 0;
    foreach( const QString& path, files )
    {
        qDebug() << "processing" << path;

        Lex lex;
        lex.lex.setStream(path);
        lex.lex.setIgnoreComments(true);
        lex.lex.setPackComments(true);
    #if 0
        Alg::Token t = lex.lex.nextToken();
        while( t.isValid() )
        {
            qDebug() << t.getString() << QString::fromUtf8(t.d_val);
            t = lex.lex.nextToken();
        }
    #else
        Alg::AstModel mdl;
        Alg::Parser2 p(&lex, &mdl);
        Alg::Declaration* module = p.RunParser();
        if( !p.errors.isEmpty() )
        {
            foreach( const Alg::Parser2::Error& e, p.errors )
                qCritical() << e.path << e.pos.d_row << e.pos.d_col << e.msg;

        }else
        {
            ok++;
            Alg::Validator v(&mdl);
            if( !v.validate(module) )
            {
                foreach( const Alg::Validator::Error& e, v.errors )
                    qCritical() << "validator:" << e.path << e.pos.d_row << e.pos.d_col << e.msg;
            }else
            {
                valid++;
                if( air )
                {
                    QFile f( path + ".air" );
                    if( !f.open(QIODevice::WriteOnly) )
                        qCritical() << "cannot open for writing:" << f.fileName();
                    else
                    {
                        QByteArray direct;
                        QBuffer buf(&direct);
                        buf.open(QIODevice::WriteOnly);
                        Air::AsmRenderer r(&buf);
                        Air::AstModel airMdl;
                        Air::AstRenderer ar(&airMdl);
                        Alg::AirGen::generateRuntime(&ar); // so that the imports resolve
                        QList<Air::AbstractRenderer*> rr;
                        rr << &r << &ar;
                        Air::RenderSplitter s(rr);
                        Alg::AirGen g(&mdl);
                        const bool res = g.generate(module, &s);
                        buf.close();
                        f.write(direct);
                        f.close();
                        if( res )
                            generated++;
                        else
                            foreach( const Alg::AirGen::Error& e, g.errors )
                                qCritical() << "airgen:" << e.path << e.pos.d_row
                                            << e.pos.d_col << e.msg;
                        if( res )
                            airValid += checkAir(path, ar, direct) ? 1 : 0;
                    }
                }
            }
        }
        if( dump && module )
            dumpAst( module, path );
    #endif

    }
    qDebug() << "#### finished with" << ok << "parsed," << valid << "validated,"
             << generated << "generated," << airValid << "air validated of total" << files.size() << "files"
             << "in" << timer.elapsed() << " [ms]";
    return 0;
}
