#ifndef __ALG_TOKENTYPE__
#define __ALG_TOKENTYPE__
// This file was automatically generated by EbnfStudio; don't modify it!


#include <QByteArray>

namespace Alg {
	enum TokenType {
		Tok_Invalid = 0,

		TT_Literals,
		Tok_Bang,
		Tok_BangEq,
		Tok_Percent,
		Tok_Amp,
		Tok_Lpar,
		Tok_Rpar,
		Tok_Star,
		Tok_2Star,
		Tok_Plus,
		Tok_Comma,
		Tok_Minus,
		Tok_MinusGt,
		Tok_Slash,
		Tok_Colon,
		Tok_ColonEq,
		Tok_Semi,
		Tok_Lt,
		Tok_Leq,
		Tok_LtGt,
		Tok_Eq,
		Tok_2Eq,
		Tok_Gt,
		Tok_Geq,
		Tok_Lbrack,
		Tok_Rbrack,
		Tok_Hat,
		Tok_HatEq,
		Tok_Bar,
		Tok_Unot,
		Tok_Umul,
		Tok_Udiv,
		Tok_Uexp,
		Tok_Uand,
		Tok_Uor,
		Tok_Uneq,
		Tok_Ueq,
		Tok_Uleq,
		Tok_Ugeq,
		Tok_Uimpl,

		TT_Keywords,
		Tok_AND,
		Tok_ARRAY,
		Tok_BEGIN,
		Tok_BOOLEAN,
		Tok_COMMENT,
		Tok_DIV,
		Tok_DO,
		Tok_ELSE,
		Tok_END,
		Tok_EQUAL,
		Tok_EQUIV,
		Tok_FALSE,
		Tok_FOR,
		Tok_GO,
		Tok_GOTO,
		Tok_GREATER,
		Tok_IF,
		Tok_IMPL,
		Tok_INTEGER,
		Tok_LABEL,
		Tok_LESS,
		Tok_MOD,
		Tok_NOT,
		Tok_NOTEQUAL,
		Tok_NOTGREATER,
		Tok_NOTLESS,
		Tok_OR,
		Tok_OWN,
		Tok_POWER,
		Tok_PROCEDURE,
		Tok_REAL,
		Tok_STEP,
		Tok_STRING,
		Tok_SWITCH,
		Tok_THEN,
		Tok_TO,
		Tok_TRUE,
		Tok_UNTIL,
		Tok_VALUE,
		Tok_WHILE,

		TT_Specials,
		Tok_decimal_number,
		Tok_unsigned_integer,
		Tok_string,
		Tok_identifier,
		Tok_basic_symbol,
		Tok_Comment,
		Tok_Eof,

		TT_MaxToken,

		TT_Max
	};

	const char* tokenTypeString( int ); // Pretty with punctuation chars
	const char* tokenTypeName( int ); // Just the names without punctuation chars
	bool tokenTypeIsLiteral( int );
	bool tokenTypeIsKeyword( int );
	bool tokenTypeIsSpecial( int );
	TokenType tokenTypeFromString( const QByteArray& str, int* pos = 0 );
}
#endif // __ALG_TOKENTYPE__
